In [1]:
from asyncio.windows_events import NULL
import time
import datetime
import requests
import pandas as pd 
import json
from pandas import json_normalize

In [2]:
timestamp=datetime.datetime.now()
def gen_dataframe (nameStartsWith,APIKEY=NULL, HASH=NULL):
    if(APIKEY==NULL and HASH==NULL):
        raise Exception("NULL values not allowed")
    else:
        REQ_URL = "http://gateway.marvel.com/v1/public/characters"
       
        parameters = { "ts": timestamp, "apikey": APIKEY, "hash": HASH,
        "nameStartsWith": nameStartsWith}
        response = requests.get(REQ_URL,params=parameters)
        data_7 = response.json()
        df_7 = pd.json_normalize(data_7,record_path=['data','results'])
        df_new = df_7[['id','name','comics.available','stories.available','events.available']]
        return df_new

In [3]:
public_key = "610b393b9916a27ef65157375c2a232d"
private_key = "822bf29e9d9c7420dae63e4785e0b7ab5ddd81cf"

In [4]:
import hashlib

In [5]:
timestamp=datetime.datetime.now()
def hash_params():
    hash_md5 = hashlib.md5()
    hash_md5.update(f'{timestamp}{private_key}{public_key}'.encode('utf-8'))
    hashe_params = hash_md5.hexdigest()
    return hashe_params

In [6]:
hash_params()

'eed8e0d5e56c8d4eb3070c14add5d3de'

In [7]:
gen_dataframe(nameStartsWith='A',APIKEY = public_key, HASH = hash_params())

,id,name,comics.available,stories.available,events.available
0,1017100,A-Bomb (HAS),4,7,0
1,1009144,A.I.M.,51,54,0
2,1010699,Aaron Stack,14,27,0
3,1009146,Abomination (Emil Blonsky),55,65,1
4,1016823,Abomination (Ultimate),2,3,0
5,1009148,Absorbing Man,96,109,4
6,1009149,Abyss,8,8,1
7,1010903,Abyss (Age of Apocalypse),3,2,1
8,1011266,Adam Destine,0,0,0
9,1010354,Adam Warlock,188,217,8
10,1010846,Aegis (Trey Rollins),0,0,0
11,1017851,Aero (Aero),29,29,0
12,1012717,Agatha Harkness,20,24,0
13,1011297,Agent Brand,29,33,0
14,1011031,Agent X (Nijo),18,23,0
15,1009150,Agent Zero,29,31,0
16,1011198,Agents of Atlas,45,52,1
17,1011175,Aginar,0,0,0
18,1011136,Air-Walker (Gabriel Lan),4,3,1
19,1011176,Ajak,4,8,1

In [8]:
result_7 =gen_dataframe(nameStartsWith='A',APIKEY = public_key, HASH = hash_params())

In [9]:
result_7.columns

Index(['id', 'name', 'comics.available', 'stories.available',
       'events.available'],
      dtype='object')

In [11]:
def gen_filter(df_63,column_name,filter):
    if filter[0]== '>':
        res_obt_df = df_63[df_63[column_name]>filter[1]]
    if filter[0]== '<':
        res_obt_df= df_63[df_63[column_name]<filter[1]]
    return res_obt_df

In [12]:
res_final = gen_filter(
    df_63= result_7,
    column_name = 'comics.available',
    filter = ['>',50]
)
res_final.head(5)

,id,name,comics.available,stories.available,events.available
1,1009144,A.I.M.,51,54,0
3,1009146,Abomination (Emil Blonsky),55,65,1
5,1009148,Absorbing Man,96,109,4
9,1010354,Adam Warlock,188,217,8